[internal] update buildscripts

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,56 +1,108 @@
 name: Release
 
 on:
-  release:
-    types:
-      - published
   workflow_dispatch:
+    inputs:
+      lastTag:
+        description: 'Previous Tag (ex: v0.1.2)'
+        required: true
+      newTag:
+        description: 'New Tag (ex: v0.1.3)'
+        required: true
+      publishToModDistributors:
+        description: 'Publish to Modrinth and CurseForge'
+        required: true
+        type: boolean
+
+permissions:
+  packages: read
+  contents: write
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  publish:
+    strategy:
+      matrix:
+        # Use these Java versions
+        java: [17]
+        # and run on both Linux and Windows
+        os: [ubuntu-22.04]
+    runs-on: ${{ matrix.os }}
 
     steps:
-      - uses: actions/cache@v2
+      # check variable has correct format
+      - name: Fail on invalid tag format
+        if: ${{ !startsWith(github.event.inputs.newTag, 'v') }}
+        run: exit 1
+
+      - name: Checkout repository
+        uses: actions/checkout@v3
         with:
-          path: |
-            ~/.gradle/loom-cache
-            ~/.gradle/caches
-            ~/.gradle/wrapper
-          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          restore-keys: |
-            gradle-
-      - uses: actions/checkout@v2
+          fetch-depth: 0
+
+      # tag preconditions
+      - name: Check existing lastTag
+        run: |
+          if git show-ref --tags --verify --quiet "refs/tags/${{ github.event.inputs.lastTag }}"; then
+            echo "lastTag exists"
+            exit 0
+          else
+            echo "lastTag doesn't exist, failing"
+            exit 1
+          fi
+      - name: Check newTag doesn't exist
+        run: |
+          if git show-ref --tags --verify --quiet "refs/tags/${{ github.event.inputs.newTag }}"; then
+            echo "newTag already exists, failing"
+            exit 1
+          else
+            echo "newTag doesn't exist"
+            exit 0
+          fi
+
+      - name: Create version tag
+        uses: actions/github-script@v6
+        with:
+          script: |
+            github.rest.git.createRef({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              ref: "refs/tags/${{ github.event.inputs.newTag }}",
+              sha: context.sha
+            })
+
+      - name: Fetch tags
+        run: git fetch --tags
+
+      - name: Fetch repo data
+        run: git fetch origin
+
       - name: Set up JDK
         uses: actions/setup-java@v1
         with:
-          java-version: 17
+          java-version: ${{ matrix.java }}
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
-      - name: Publish to GitHub Package Registry
-        run: ./gradlew build publish
+      - name: Publish to GitHub Package Registry and GitHub Release
+        run: ./gradlew build generateChangelog publish githubRelease -PlastTag="${{ github.event.inputs.lastTag }}" -PnewTag="${{ github.event.inputs.newTag }}"
         env:
           GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Create and add artifacts to GitHub Release
-        uses: Kir-Antipov/mc-publish@v3.3
-        with:
-          loaders: |
-            fabric
-            quilt
-
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          github-generate-changelog: true
-
-      - name: Publish to Modrinth
-        run: ./gradlew build modrinth
+      - name: Publish to Modrinth and Curseforge
+        run: ./gradlew build generateChangelog publishMods -PlastTag="${{ github.event.inputs.lastTag }}" -PnewTag="${{ github.event.inputs.newTag }}"
+        if: ${{ github.event.inputs.publishToModDistributors == 'true' }}
         env:
+          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
-
-      - name: Publish to CurseForge
-        run: ./gradlew build curseforge
-        env:
           CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
+
+      - name: Capture build artifacts
+        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from LTS java on one OS
+        uses: actions/upload-artifact@v3
+        with:
+          name: Artifacts
+          path: |
+            build/libs/
